=== sknlsake20/classcontent-assignments/13-09-2021/bank.dtd
<!NOTATION JPG SYSTEM "image/jpeg">
<!NOTATION GIF SYSTEM "image/gif">
<!ENTITY sk "shivaisgoodtutorial">
<!ELEMENT bank (branch+,loan+,customer+,photo)>
<!ELEMENT branch EMPTY>
<!ATTLIST branch bid ID #REQUIRED>
<!ATTLIST branch bname CDATA #IMPLIED>
<!ATTLIST branch bcode  CDATA "5678">
<!ELEMENT loan EMPTY>
<!ATTLIST loan lid ID #REQUIRED>
<!ELEMENT customer (account+)>
<!ELEMENT account EMPTY>
<!ATTLIST account no ID #REQUIRED>
<!ATTLIST account bbid IDREFS #REQUIRED>
<!ATTLIST account type (SAVING | CURRENT | TRADING) #REQUIRED>
<!ATTLIST account emailid CDATA #IMPLIED>
<!ELEMENT photo (#PCDATA)>
<!ATTLIST photo pht-type NOTATION (JPG|GIF) #REQUIRED>

=== sknlsake20/classcontent-assignments/13-09-2021/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bank PUBLIC "-//shiva//1.0//EN" "bank.dtd">
<bank>
<branch bid="t456" bname="TN"></branch>
<branch bid="h556" bname="HYD"></branch>
<loan lid="p67878"></loan>
<customer>
<account no="j234" bbid="t456 p67878" type="SAVING"></account>
<account no="j255" bbid="h556 p67878" type="SAVING" emailid="shiv@gmail.com"></account>
</customer>
<photo pht-type="GIF">this is for photo &sk;</photo>
</bank>
