=== sknlsake20/classcontent-assignments/13-09-2021/books.dtd
<!ELEMENT books (book+)>
<!ELEMENT book (book-name,price,author+,publisher?)>
<!ELEMENT book-name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher EMPTY>
<!ATTLIST publisher pid CDATA #REQUIRED>
<!ATTLIST publisher pname CDATA #FIXED "sarvesh">
<!ATTLIST publisher paddress CDATA #IMPLIED>
<!ATTLIST publisher ppin CDATA "231">

=== sknlsake20/classcontent-assignments/13-09-2021/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books PUBLIC " " "books.dtd">
<books> 
  <book>
    <book-name>java</book-name>
    <price>1000</price>
    <author>shiva</author>
    <publisher pid="345" pname="sarvesh"></publisher>
  </book>
  
    <book>
    <book-name>cpp</book-name>
    <price>500</price>
    <author>shalini</author>
    <publisher pid="221" paddress="chennai"></publisher>
  </book>
</books>
