=== sknlsake20/classcontent-assignments/13-09-2021/emp.dtd
<!ELEMENT employees (employee)>
<!ELEMENT employee ((employeename | employeeid),(employeeage),(employeeaddress))>
<!ELEMENT employeename (#PCDATA)>
<!ELEMENT employeeid (#PCDATA)>
<!ELEMENT employeeage EMPTY>
<!ATTLIST employeeage  age CDATA #REQUIRED>
<!ELEMENT employeeaddress (#PCDATA | cityname | state |pin)*>
<!ELEMENT cityname (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT pin (#PCDATA)>

=== sknlsake20/classcontent-assignments/13-09-2021/employee-extenternaldtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees PUBLIC "-//shiva//1.0//EN" "emp.dtd">
<employees>
 <employee>
  <employeename>shiva</employeename>
  <employeeage age="17"></employeeage>
  <employeeaddress>
  <cityname>hyd</cityname>
  <state>TS</state>
  <pin>500080</pin>  
</employeeaddress>
</employee>
</employees>
